version: 0.0
os: linux
files:
  - source: /home/ubuntu
    destination: /home/ubuntu/spring-boot

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: unbuntu
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: unbuntu
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: unbuntu
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: unbuntu
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: unbuntu