name: Deploy to AWS CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
#    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIA3FLDXANFKYUEH2VY
          aws-secret-access-key: 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
          aws-region: ap-northeast-2  # 필요에 따라 AWS 리전을 조정하세요

      - name: Deploy to AWS CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name TestWebSourceDeploy \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name TestWeb-1 \
            --description "GitHub Actions deployment" \
            --github-location repository=DaolFn/backend,commitId=${{ github.sha }}